sudo: required

language: go
go:
  - 1.x

services:
  - docker

script:
  - go test bibliotheekbe/*.go
  - docker build -t maartje/readmyage-api ./

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
    docker push maartje/readmyage-api;
    fi
